language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"

install:
    - python setup.py --quiet install

script:
    - python test_unify.py

after_success:
    - pip install --quiet coverage
    - coverage run test_unify.py
    - coverage report --show-missing --omit='*/distutils/*'; true
